### ISSUE TITLE
Add version number to app 'Properties' in Windows Explorer

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/hebi-scope-feedback#18]
Maybe this is already fixed.  In recent packaged versions on Windows there was no version number under Properities->Details.  macOS version is listed on 'Get Info'

**Comment by ennerf** [comment]
I added all fields that are available to me. I'm not sure what that "File Version" really shows, but there doesn't seem to be a way for met to set it.

**Comment by daverolli** [comment]
Is this really closed?  Every other app in Windows shows some combo of Product Name / Product Version / File Version.  It's good that we have the version visible at least in the app header, but to me this issue is still open.

**Comment by ennerf** [comment]
The executable is generated by the packager, so it's outside my control. I am already setting all `vendor` etc. options that I found, but none of those seem to set the explorer properties. I couldn't find anything else in the [available API](https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javapackager.html).

I did try https://stackoverflow.com/questions/284258/how-do-i-set-the-version-information-for-an-existing-exe-dll, but that doesn't work either.

Thus, I know it's working, but I closed it because I don't think that there is anything I can do other than waiting for the API to change, or to switch to a commercial packager (which may or may not support it either).

**Comment by ennerf** [comment]
It may also be possible to do this via an Installer. Would it be worth setting that up?

**Comment by daverolli** [comment]
I don't think it needs to get fixed right away, but it is still an open issue, even if it can't be easily solved in the near term.

**Comment by rLinks234** [comment]
It looks like javapackager uses a small [launcher exe](https://github.com/teamfx/openjfx-8u-dev-rt/blob/master/modules/fxpackager/src/main/native/launcher/win/WinLauncher.cpp) which hooks into `libpackager.so`/`packager.dll` to init the JVM using JNI. It _could_ be as simple as recompiling that single file in a visual studio project while providing the version info

**Comment by ennerf** [comment]
Could potentially be fixed with [ResourceHacker](http://www.angusj.com/resourcehacker/), which can change the properties of an existing .exe.

**Comment by ennerf** [comment]
the new jpackager does this
